using LabSync.Core.ValueObjects;
using System.ComponentModel.DataAnnotations;
using System;

namespace LabSync.Core.Dto
{
    /// <summary>
    /// Payload sent by the Agent during the first startup/installation.
    /// </summary>
    public class RegisterAgentRequest
    {
        /// <summary>
        /// Physical hardware address. Must match the format XX:XX:XX:XX:XX:XX.
        /// </summary>
        [Required]
        [RegularExpression(@"^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$", ErrorMessage = "Invalid MAC Address format.")]
        public string MacAddress { get; set; } = string.Empty;

        /// <summary>
        /// Network hostname (e.g., "DESKTOP-ABC12").
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string Hostname { get; set; } = string.Empty;

        /// <summary>
        /// Operating System family (Windows/Linux).
        /// </summary>
        [Required]
        public DevicePlatform Platform { get; set; }

        /// <summary>
        /// Detailed OS version (e.g., "Ubuntu 22.04" or "Windows 11 22H2").
        /// </summary>
        [MaxLength(200)]
        public string OsVersion { get; set; } = string.Empty;

        /// <summary>
        /// Current local IP address (optional, for diagnostics).
        /// </summary>
        [MaxLength(45)]
        public string? IpAddress { get; set; }
    }

    /// <summary>
    /// Server response containing authentication credentials.
    /// </summary>
    public class RegisterAgentResponse
    {
        /// <summary>
        /// Unique Device ID generated by the database.
        /// </summary>
        public Guid DeviceId { get; set; }

        /// <summary>
        /// API Token (JWT) that the Agent must use for all future requests.
        /// </summary>
        public string Token { get; set; } = string.Empty;
    }
}